# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cassey's Thoughts
description: > # this means to ignore newlines until "baseurl:"
  Community health engineer at [Glitch](https://glitch.com), keeping it the friendly place to create the app of your dreams. [Running for City Council](http://casseyforcouncil.com) in Lincoln, NE.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clottman.github.io" # the base hostname & protocol for your site
twitters: [
  {
    username: CasseyLottman,
    display: "Personal Twitter",
  },
  {
    username: CasseyLNK,
    display: "Campaign Twitter",
  }
]
github_username:  clottman
glitch_username: cassey
image_url: "/assets/images"

# Build settings
markdown: kramdown
exclude: [node_modules]

collections:
  - tag_pages

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "posts/:num"
