# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cassey's Thoughts
description: > # this means to ignore newlines until "baseurl:"
  This is my place to talk technology. Warning: you may encounter politics. You're going to get through it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clottman.github.io" # the base hostname & protocol for your site
twitter_username: CasseyLottman
github_username:  clottman
image_url: "/assets/images"

# Build settings
markdown: kramdown
exclude: [node_modules]

collections:
  - tags